# This workflow automatically creates a GitHub release for the project on successful version update

name: Create a GitHub release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PS2EXE
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ps2exe

      - name: Build x86 release
        shell: powershell
        run: |
          ps2exe .\Winit\main.ps1 .\winit_x86.exe -x86 -verbose -version ${{ github.ref_name }} -title Winit -description "Helper utility for installing software on new Windows installs" -company "Team DeltaV" -product Winit -copyright "Lari Liuhamo 2023" -trademark "Team DeltaV"

      - name: Build x64 release
        shell: powershell
        run: |
          ps2exe .\Winit\main.ps1 .\winit_x64.exe -x64 -verbose -version ${{ github.ref_name }} -title Winit -description "Helper utility for installing software on new Windows installs" -company "Team DeltaV" -product Winit -copyright "Lari Liuhamo 2023" -trademark "Team DeltaV"

      - name: Upload builds
        uses: actions/upload-artifact@v3
        with:
          name: built-binary
          path: |
            .\Winit\*.exe

  release:
    name: Create Release
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-binary

      - name: Check Version
        uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Check for Pre-release
        uses: haya14busa/action-cond@v1
        id: is_prerelease
        with:
          cond: ${{ steps.version.outputs.prerelease != '' }}
          if_true: true
          if_false: false
      
      - name: Install Python to Parse the Changelog
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get Newest Changelog
        run: |
          py -c "import re; from pathlib import Path; text=re.sub('<!--(.*?)-->', '', (Path.cwd() / 'CHANGELOG.md').read_text(), flags=re.DOTALL); start=text.find('_' * 79); (Path.cwd() / 'TEMP_CHANGELOG.md').write_text(text[start:text.find('_' * 79, start+1)])"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ steps.is_prerelease.outputs.value }}
          body_path: ./TEMP_CHANGELOG.md
          files: |
            *.exe
